paths:
  raw_mat_dirs:
    - "C:/Users/user/Downloads/SAIIT/SAIIT"
  behavioral_mat_dirs:
    - "E:/intern/SAIIT_behavioural/SAIIT_behavioural"
  cleaned_data_dir: "e:/intern/cleaned_data"
  ica_plot_dir: "e:/intern/ica_plots"
  features_dir: "e:/intern/features"
  erp_plot_dir: "e:/intern/erp_plots"
  epochs_dir: "e:/intern/epochs"
  plv_viz_dir: "e:/intern/plv_viz"
  qa_log_dir: "e:/intern/qa_logs"
  erp_visualizations: "e:/intern/erp_visualizations"
  tfr_data_dir: "e:/intern/tfr_data"
  rt_csv: "e:/intern/outputs/behavioral_reaction_times.csv"
  label_csv: "e:/intern/outputs/reaction_time_labels.csv"
  merged_dataset: "e:/intern/outputs/merged_graph_features_with_labels.csv"
  graph_features_csv: "e:/intern/plv_graph_features_ALL_FILES.csv"
  graph_features_csv_dir: "e:/intern/features/plv_graph_features"
  event_csv: "e:/intern/outputs/event_timeline.csv"
  subjects_dir: "C:/Users/user/mne_data/MNE-fsaverage-data"

preprocessing:
  sfp_path: "E:/intern/GSN_HydroCel_129.sfp"
  bandpass_filter:
    l_freq: 1.0
    h_freq: 40.0
  ica:
    n_components: 15
    random_state: 97
    max_iter: 512
  annotate_peak_to_peak_threshold: 100e-6

epoching:
  tmin: -0.3
  tmax: 1.5
  baseline: [-0.3, 0]

params:
  sfreq: 500
  window_size: 0.3
  step_size: 0.05
  plv_threshold: 0.85

source_localization:
  parcellation: Schaefer2018_100Parcels_7Networks
  hemi: both

graph_window:
  length_ms: 300
  step_ms: 150
  band: [4, 8]
  threshold: 0.5
  features: [degree, clustering, efficiency]
  out_dir: e:/intern/features/plv_graph_features

event_labels:
  1: "Eyes Open"
  2: "Eyes Closed"
  5: "Response - Left_Yes"
  8: "Response - Right_No"
  9: "No Response"
  11: "Visual Condition A"
  12: "Stimulus Condition 1"
  13: "Stimulus Condition 2"
  82: "Feedback"
  94: "End - Contrast Detection"
  95: "End - Sequence Learning"
  96: "End - Symbol Search"
  100: "Movie 1 Start"
  102: "Movie 2 Start"
  111: "Movie 3 Start"
  112: "Movie 4 Start"
  9999: "Bad Segment"
